require "awesome/definitions/bits" unless defined?(Awesome::Definitions::Bits)
require "awesome/definitions/locales" unless defined?(Awesome::Definitions::Locales)
require "awesome/definitions/filters" unless defined?(Awesome::Definitions::Filters)
require "awesome/definitions/stopwords" unless defined?(Awesome::Definitions::Stopwords)
require "awesome/definitions/types" unless defined?(Awesome::Definitions::Types)
require "awesome/triage" unless defined?(Awesome::Triage)
require "awesome/search" unless defined?(Awesome::Search)
require "awesome/super_search" unless defined?(Awesome::SuperSearch)
